---
# yamllint disable rule:comments rule:line-length
name: Java CI
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions: {}
jobs:
  lint:
    name: "\U0001F9F9 Linters"
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      issues: write
      pull-requests: write
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Build
        run: ./mvnw --no-transfer-progress -V -B -fae verify
