---
# yamllint disable rule:comments rule:line-length
name: Tag Release
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
jobs:
  trigger-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: "zulu"
          java-version: "21"
          cache: maven
      - name: Tag release
        run: |
          VERSION=$(./mvnw help:evaluate -q -B -ntp -Dexpression=project.version -DforceStdout=true)
          git config --global committer.email "48418865+dropwizard-committers@users.noreply.github.com"
          git config --global committer.name "Dropwizard Release Action"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
